const db = require('../config/connection');
const { User, Sneaker } = require('../models');

db.once('open', async () => {
  await Sneaker.deleteMany();

  const sneakers = await Sneaker.insertMany([
    {
      brand: 'Nike',
      model: 'Air Max 90',
      name: 'Air Max 90 OG Infrared',
      gender: 'Unisex',
      sizes: [
        { size: 8, quantity: 10 },
        { size: 9, quantity: 15 },
        { size: 10, quantity: 20 },
        { size: 11, quantity: 15 },
      ],
      price: 120,
      description: 'The iconic Air Max 90 in its original Infrared colorway.',
      imageUrl: '/assets/AirMax-90-OG-Infrared/airmaxInfrared.png',  // Updated this line
      category: 'Lifestyle',
      releaseDate: new Date('2020-12-01'),
      recommended: true,
      onSale: false,
    },
    {
      brand: 'Nike',
      model: 'Air Max 1',
      name: 'Air Max 1 Anniversary Red',
      gender: 'Men',
      sizes: [
        { size: 8, quantity: 8 },
        { size: 9, quantity: 12 },
        { size: 10, quantity: 18 },
        { size: 11, quantity: 10 },
      ],
      price: 140,
      description: 'Celebrating the original colorway of the Air Max 1.',
      imageUrl: 'https://example.com/airmax1-anniversary-red.jpg',
      category: 'Lifestyle',
      releaseDate: new Date('2021-03-26'),
      recommended: false,
      onSale: true,
      salePrice: 119.99,
    },
    {
      brand: 'Nike',
      model: 'Dunk Low',
      name: 'Dunk Low Retro White Black',
      gender: 'Unisex',
      sizes: [
        { size: 7, quantity: 10 },
        { size: 8, quantity: 15 },
        { size: 9, quantity: 20 },
        { size: 10, quantity: 15 },
      ],
      price: 100,
      description: 'A classic two-tone Dunk Low in white and black.',
      imageUrl: 'https://example.com/dunk-low-white-black.jpg',
      category: 'Skateboarding',
      releaseDate: new Date('2021-01-14'),
    },
    {
      brand: 'Air Jordan',
      model: 'Jordan 4 Retro',
      name: 'Jordan 4 Retro Fire Red',
      gender: 'Men',
      sizes: [
        { size: 8, quantity: 5 },
        { size: 9, quantity: 10 },
        { size: 10, quantity: 15 },
        { size: 11, quantity: 10 },
        { size: 12, quantity: 5 },
      ],
      price: 200,
      description: 'The Jordan 4 Retro returns in its classic Fire Red colorway.',
      imageUrl: '/assets/Jordan-4-Retro-Fire-Red/jordanRetroFire.png',
      category: 'Basketball',
      releaseDate: new Date('2020-11-28'),
      recommended: true,
      onSale: false,
    },
    {
      brand: 'Air Jordan',
      model: 'Jordan 4 Retro',
      name: 'Jordan 4 Retro University Blue',
      gender: 'Men',
      sizes: [
        { size: 8, quantity: 5 },
        { size: 9, quantity: 10 },
        { size: 10, quantity: 15 },
        { size: 11, quantity: 10 },
        { size: 12, quantity: 5 },
      ],
      price: 200,
      description: 'Inspired by Michael Jordans alma mater, UNC.',
      imageUrl: 'https://example.com/jordan4-university-blue.jpg',
      category: 'Basketball',
      releaseDate: new Date('2021-04-28'),
    },
    {
      brand: 'Nike',
      model: 'Air Force 1',
      name: 'Air Force 1 Low White',
      gender: 'Unisex',
      sizes: [
        { size: 6, quantity: 10 },
        { size: 7, quantity: 15 },
        { size: 8, quantity: 20 },
        { size: 9, quantity: 25 },
        { size: 10, quantity: 20 },
        { size: 11, quantity: 15 },
        { size: 12, quantity: 10 },
      ],
      price: 90,
      description: 'The classic all-white Air Force 1 Low.',
      imageUrl: 'https://example.com/airforce1-white.jpg',
      category: 'Lifestyle',
      releaseDate: new Date('2020-01-01'),
    },
    {
      brand: 'Air Jordan',
      model: 'Jordan 1 Retro High',
      name: 'Jordan 1 Retro High OG Chicago',
      gender: 'Men',
      sizes: [
        { size: 8, quantity: 5 },
        { size: 9, quantity: 8 },
        { size: 10, quantity: 12 },
        { size: 11, quantity: 8 },
        { size: 12, quantity: 5 },
      ],
      price: 170,
      description: 'The iconic Jordan 1 in the classic Chicago colorway.',
      imageUrl: 'https://example.com/jordan1-chicago.jpg',
      category: 'Basketball',
      releaseDate: new Date('2022-11-19'),
    },
    {
      brand: 'Nike',
      model: 'Air Max 97',
      name: 'Air Max 97 Silver Bullet',
      gender: 'Unisex',
      sizes: [
        { size: 7, quantity: 8 },
        { size: 8, quantity: 12 },
        { size: 9, quantity: 15 },
        { size: 10, quantity: 12 },
        { size: 11, quantity: 8 },
      ],
      price: 180,
      description: 'The futuristic Air Max 97 in its original Silver Bullet colorway.',
      imageUrl: 'https://example.com/airmax97-silver-bullet.jpg',
      category: 'Lifestyle',
      releaseDate: new Date('2022-12-14'),
    },
    {
      brand: 'Air Jordan',
      model: 'Jordan 11 Retro',
      name: 'Jordan 11 Retro Concord',
      gender: 'Men',
      sizes: [
        { size: 8, quantity: 5 },
        { size: 9, quantity: 10 },
        { size: 10, quantity: 15 },
        { size: 11, quantity: 10 },
        { size: 12, quantity: 5 },
      ],
      price: 220,
      description: 'The beloved Jordan 11 in the classic Concord colorway.',
      imageUrl: 'https://example.com/jordan11-concord.jpg',
      category: 'Basketball',
      releaseDate: new Date('2018-12-08'),
    },
    {
      brand: 'Nike',
      model: 'React Element 87',
      name: 'React Element 87 Sail Light Bone',
      gender: 'Unisex',
      sizes: [
        { size: 7, quantity: 8 },
        { size: 8, quantity: 12 },
        { size: 9, quantity: 15 },
        { size: 10, quantity: 12 },
        { size: 11, quantity: 8 },
      ],
      price: 160,
      description: 'A modern classic featuring React foam and a translucent upper.',
      imageUrl: '/assets/React-Element-87-Sail/reactElementSail.png',
      category: 'Lifestyle',
      releaseDate: new Date('2018-10-11'),
      recommended: true,
      onSale: true,
      salePrice: 129.99,
    },
  ]);

  console.log('Sneakers seeded');

  process.exit();
});
